// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: tables.sql

package db

import (
	"context"
)

const getDummies = `-- name: GetDummies :many
select id, name from dummy
`

func (q *Queries) GetDummies(ctx context.Context) ([]Dummy, error) {
	rows, err := q.db.QueryContext(ctx, getDummies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dummy
	for rows.Next() {
		var i Dummy
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
